### ISSUE TITLE
Complex datasets

### ISSUE THREAD

**Issue by borela** [mattphillips/jest-each#1]
First, thank you for this library, it made my tests cleaner.

Sometimes the datasets are too complex to print in the test description, is it possible to print the row being tested if a test fails?

```js
let complexData = [
  [{ complexObject, ... }, expectedValue],
  [{ complexObject, ... }, expectedValue]
]
```
I basically need to print the complex object only if the test fails.

**Comment by tgfischer** [comment]
I ran into the same problem. To get around this, I passed in a message

```javascript
each([
  [
    "should pass when input is bar",
    {
      foo: "bar"
    },
    expectedValue
  ]
]).it("%s", (message, params, expectedValue) => {
  // ...
});
```

**Comment by mattphillips** [comment]
@borela @tgfischer in `jest-each@23` I've added support for pretty formatting with `%p`. jest-each has also been migrated over to the core Jest repo and is available in Jest@23 as `test.each` see https://facebook.github.io/jest/docs/en/api.html#testeachtable-name-fn
